### ISSUE TITLE
Following up after release of WordPress plugin

### ISSUE THREAD

**Issue by scripting** [scripting/feedlandBlogrollToolkit#11]
It's been a week since the [release of the WordPress plugin](http://scripting.com/2024/04/24/132025.html) for blogrolls, and I'm coming back around to have a look at where we're at.

I'm going to tweak the custom CSS, but for now not change the CSS in the release, to make it look better in scripting.com. 

So in this thread I'm going share the CSS changes I'm making only specific to scripting.com.

**Comment by scripting** [comment]
So here are the changes I just made. 

```css
.divBlogrollContainer, #idBlogrollContainer {
	border: 1px solid silver;
	padding-left: 2px;
	padding-right: 2px;
	}
.divQuietBlogroll .trBlogrollFeed td {
	padding-top: 3px;
	padding-bottom: 3px;
	}

```
