### ISSUE TITLE
Bootstrap styles colliding with themes

### ISSUE THREAD

**Issue by NickGreen** [scripting/feedlandBlogrollToolkit#6]
## Synopsis

While testing the plugin on production sites, we noticed that when the plugin is activated, it is breaking the styles and layout of the themes. We've found that this is the result of `bootstrap.css` being so wide-ranging in its selectors. 

We definitely don't want the activation of the plugin to collide so broadly with WordPress themes, and so we need to figure out how to get more specific with our CSS.

### Screenshots
![SCR-20240401-oaqx](https://github.com/scripting/feedlandBlogrollToolkit/assets/2067992/259100fe-3eb8-4366-a749-b53a2f0e10af)

![SCR-20240401-oams](https://github.com/scripting/feedlandBlogrollToolkit/assets/2067992/29ec29e4-e4ff-467c-90a7-4af3cfdbc9dd)

## Possible solutions

1. It might be possible to wrap the entire bootstrap CSS in a specific selector, like `#divBlogrollContainer`. Bootstrap 2.3.1, which is currently being loaded, used Less as a compiler, so we'd need to research how to get that working.
2. We might be able to just pull out the specific styles from bootstrap.css that are needed for the blogrolls to work, such as the dropdowns and tooltips, and wrap those in a selector, and then get rid of the superfluous styles.

**Comment by fmfernandes** [comment]
I found a nice way of trying to find which CSS is being used or not, you can read more about it here: https://developer.chrome.com/docs/devtools/coverage. 

So, using that method, I've set up a test site locally and added the blogroll plugin to a page and looked for the `https://s3.amazonaws.com/scripting.com/code/includes/bootstrap.css` file and ran a report for it. Looks like ~90% of the file contents are unused. If you click on the Download button (<img width="16" alt="Download" src="https://github.com/scripting/feedlandBlogrollToolkit/assets/24195829/d9a6f07b-ee50-4e92-8c88-3c723902fe22">) Chrome will generate a `.json` file with ranges of unused bytes in the file.

I created a simple PHP script to parse those and echo only the used bytes:

```php
<?php

$file = 'coverage.json';

$coverage_entries = json_decode( file_get_contents( $file ), true);

if ( ! isset( $argv[1] ) ) {
	echo 'Usage: php coverage.php <url>' . PHP_EOL;
	exit( 1 );
}

foreach ( $coverage_entries as $entry ) {
	if ( $entry['url'] !== $argv[1] ) {
		continue;
	}

	$used_css = '';
	foreach ( $entry['ranges'] as $range ) {
		$used_css .= substr( $entry['text'], $range['start'], $range['end'] - $range['start'] ) . PHP_EOL;
	}

	echo $used_css . PHP_EOL;
}
```

You'd use it like this: `php coverage.php 'https://s3.amazonaws.com/scripting.com/code/includes
/bootstrap.css?ver=1.0.0'` while having downloaded the coverage report and saved it as `coverage.json` in the same folder as the PHP script.

This is the final output:

<details><summary>CSS file</summary>
<p>

```css
article,
  aside,
  details,
  figcaption,
  figure,
  footer,
  header,
  hgroup,
  nav,
  section {
        display: block;
  }
html {
        font-size: 100%;
        -webkit-text-size-adjust: 100%;
                -ms-text-size-adjust: 100%;
  }
a:focus {
        outline: thin dotted #333;
        outline: 5px auto -webkit-focus-ring-color;
        outline-offset: -2px;
  }
a:hover,
  a:active {
        outline: 0;
  }
button,
  input,
  select,
  textarea {
        margin: 0;
        font-size: 100%;
        vertical-align: middle;
  }
button,
  input {
        *overflow: visible;
        line-height: normal;
  }
button,
  html input[type="button"],
  input[type="reset"],
  input[type="submit"] {
        cursor: pointer;
        -webkit-appearance: button;
  }
label,
  select,
  button,
  input[type="button"],
  input[type="reset"],
  input[type="submit"],
  input[type="radio"],
  input[type="checkbox"] {
        cursor: pointer;
  }
body {
        margin: 0;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        font-size: 14px;
        line-height: 20px;
        color: #333333;
        background-color: #ffffff;
  }
a {
        color: #0088cc;
        text-decoration: none;
  }
a:hover,
  a:focus {
        color: #005580;
        text-decoration: underline;
  }
p {
        margin: 0 0 10px;
  }
h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
        margin: 10px 0;
        font-family: inherit;
        font-weight: bold;
        line-height: 20px;
        color: inherit;
        text-rendering: optimizelegibility;
  }
h1,
  h2,
  h3 {
        line-height: 40px;
  }
h1 {
        font-size: 38.5px;
  }
h2 {
        font-size: 31.5px;
  }
h3 {
        font-size: 24.5px;
  }
ul,
  ol {
        padding: 0;
        margin: 0 0 10px 25px;
  }
li {
        line-height: 20px;
  }
label,
  input,
  button,
  select,
  textarea {
        font-size: 14px;
        font-weight: normal;
        line-height: 20px;
  }
input,
  button,
  select,
  textarea {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  }
table {
        max-width: 100%;
        background-color: transparent;
        border-collapse: collapse;
        border-spacing: 0;
  }
.dropup,
  .dropdown {
        position: relative;
  }
.dropdown-toggle {
        *margin-bottom: -3px;
  }
.dropdown-toggle:active,
  .open .dropdown-toggle {
        outline: 0;
  }
.dropdown-menu {
        position: absolute;
        top: 100%;
        left: 0;
        z-index: 1000;
        display: none;
        float: left;
        min-width: 160px;
        padding: 5px 0;
        margin: 2px 0 0;
        list-style: none;
        background-color: #ffffff;
        border: 1px solid #ccc;
        border: 1px solid rgba(0, 0, 0, 0.2);
        *border-right-width: 2px;
        *border-bottom-width: 2px;
        -webkit-border-radius: 6px;
           -moz-border-radius: 6px;
                        border-radius: 6px;
        -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
           -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
                        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        -webkit-background-clip: padding-box;
           -moz-background-clip: padding;
                        background-clip: padding-box;
  }
.dropdown-menu .divider {
        *width: 100%;
        height: 1px;
        margin: 9px 1px;
        *margin: -5px 0 5px;
        overflow: hidden;
        background-color: #e5e5e5;
        border-bottom: 1px solid #ffffff;
  }
.dropdown-menu > li > a {
        display: block;
        padding: 3px 20px;
        clear: both;
        font-weight: normal;
        line-height: 20px;
        color: #333333;
        white-space: nowrap;
  }
.dropdown-menu > li > a:hover,
  .dropdown-menu > li > a:focus,
  .dropdown-submenu:hover > a,
  .dropdown-submenu:focus > a {
        color: #ffffff;
        text-decoration: none;
        background-color: #0081c2;
        background-image: -moz-linear-gradient(top, #0088cc, #0077b3);
        background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#0088cc), to(#0077b3));
        background-image: -webkit-linear-gradient(top, #0088cc, #0077b3);
        background-image: -o-linear-gradient(top, #0088cc, #0077b3);
        background-image: linear-gradient(to bottom, #0088cc, #0077b3);
        background-repeat: repeat-x;
        filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ff0088cc', endColorstr='#ff0077b3', GradientType=0);
  }
.open {
        *z-index: 1000;
  }
.open > .dropdown-menu {
        display: block;
  }
.fade {
        opacity: 0;
        -webkit-transition: opacity 0.15s linear;
           -moz-transition: opacity 0.15s linear;
                 -o-transition: opacity 0.15s linear;
                        transition: opacity 0.15s linear;
  }
.fade.in {
        opacity: 1;
  }
.tooltip {
        position: absolute;
        z-index: 1030;
        display: block;
        font-size: 11px;
        line-height: 1.4;
        opacity: 0;
        filter: alpha(opacity=0);
        visibility: visible;
  }
.tooltip.in {
        opacity: 0.8;
        filter: alpha(opacity=80);
  }
.tooltip.right {
        padding: 0 5px;
        margin-left: 3px;
  }
.tooltip-inner {
        max-width: 200px;
        padding: 8px;
        color: #ffffff;
        text-align: center;
        text-decoration: none;
        background-color: #000000;
        -webkit-border-radius: 4px;
           -moz-border-radius: 4px;
                        border-radius: 4px;
  }
.tooltip-arrow {
        position: absolute;
        width: 0;
        height: 0;
        border-color: transparent;
        border-style: solid;
  }
.tooltip.right .tooltip-arrow {
        top: 50%;
        left: 0;
        margin-top: -5px;
        border-right-color: #000000;
        border-width: 5px 5px 5px 0;
  }
.popover {
        position: absolute;
        top: 0;
        left: 0;
        z-index: 1010;
        display: none;
        max-width: 276px;
        padding: 1px;
        text-align: left;
        white-space: normal;
        background-color: #ffffff;
        border: 1px solid #ccc;
        border: 1px solid rgba(0, 0, 0, 0.2);
        -webkit-border-radius: 6px;
           -moz-border-radius: 6px;
                        border-radius: 6px;
        -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
           -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
                        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        -webkit-background-clip: padding-box;
           -moz-background-clip: padding;
                        background-clip: padding-box;
  }
.popover.right {
        margin-left: 10px;
  }
.popover-title {
        padding: 8px 14px;
        margin: 0;
        font-size: 14px;
        font-weight: normal;
        line-height: 18px;
        background-color: #f7f7f7;
        border-bottom: 1px solid #ebebeb;
        -webkit-border-radius: 5px 5px 0 0;
           -moz-border-radius: 5px 5px 0 0;
                        border-radius: 5px 5px 0 0;
  }
.popover-title:empty {
        display: none;
  }
.popover-content {
        padding: 9px 14px;
  }
.popover .arrow,
  .popover .arrow:after {
        position: absolute;
        display: block;
        width: 0;
        height: 0;
        border-color: transparent;
        border-style: solid;
  }
.popover .arrow {
        border-width: 11px;
  }
.popover .arrow:after {
        border-width: 10px;
        content: "";
  }
.popover.right .arrow {
        top: 50%;
        left: -11px;
        margin-top: -11px;
        border-right-color: #999;
        border-right-color: rgba(0, 0, 0, 0.25);
        border-left-width: 0;
  }
.popover.right .arrow:after {
        bottom: -10px;
        left: 1px;
        border-right-color: #ffffff;
        border-left-width: 0;
  }
```

</p>
</details> 

This could probably use a little bit more refining, i.e. adding a parent container for all the elements `#divBlogrollContainer` and/or also removing generic elements like, `h2`,  `h3`, `aside`, `details`, `input`, etc. that the blogroll doesn't use.

Then, in the plugin we could ship this file instead of grabbing from `https://s3.amazonaws.com/scripting.com/code/includes/bootstrap.css`. Since those are used mostly for base styles and we override some on the `blogroll.css` file, I don't think it's an issue if we ship it with the plugin.

---

This method mainly adresses the solution **#⁠2** proposed by @NickGreen above.

What do you guys think?
